### ISSUE TITLE
Wands and Spells mod

### ISSUE THREAD

**Issue by VanCock** [Ayutac/magic#4]
Howdy, (I hope it's the correct GitHub) I have played with your amazing magic mod, it's quite good, but I have few minor complains, first of all bolt spell type doesn't seem to work at all, it shoots projectile yes, but the projectile itself doesn't really deal any damage, if we talk about the projectiles then maybe consider improving them, add some particles, maybe work on how they look in general (optionally do the same to wands), because for now they look kinda boring and magic isn't boring, a lot of spells work but in very bad way, water dome works just fine, but it's just annoying on it's own, earth removal targets only dirt and doesn't give a shit about grass or stone, pillar and circle stone spells have somewhat same problem (or they just don't work at all, hard to tell), lastly mana system, it's rather pointless I would say given you can have only single spell on wand and you can't really spam them nor spells are very powerful, I recommend removing it and instead just extend recharge of wand (more mana spell would take = more time you will have to wait to cast it again) it seems better , it's just annoying and if you play with many magic mods then it's just another mana you have to keep up with, other than that it's great, simple yet fun, will be great for early game spell system, just a proposition but maybe add magic armour sets and definitely more spells plus maybe make spell books of specific type (fire, air, earth, etc.) look different so you can tell by just looking at the book what spell type it is, anyway that's all I wanted to say, again great mod, have a good one buddy and take care of yourself.    :)

**Comment by Ayutac** [comment]
This is a lot, let me take it bit by bit

> but the projectile itself doesn't really deal any damage

Intended. You can change the damage via configs or game rules

> add some particles, maybe work on how they look in general

If you can help with these render issues, you are welcome to PR

> earth removal targets only dirt and doesn't give a shit about grass or stone

Not working on grass is intended. It should work on stone though. Just tested and it works fine. If you are sure it doesn't work on Stone or Cobblestone, open an issue for that alone please. It is also not supposed to work on e.g. Stonebricks. All blocks it should work on are in magic/tags/block/earth.json. In a modpack you can add other appropiate blocks.

> pillar and circle stone spells have somewhat same problem

same thing, same tag. Shoot pillar on Stone or Netherrack or Endstone. Earth Circle can only raise earth/stone when there is some nearby, else it doesn't work of course.

> lastly mana system, it's rather pointless

I disagree.

> you can't really spam them

Wand cooldown is another gamerule you can change

> it's just annoying and if you play with many magic mods then it's just another mana you have to keep up with

I'm open for compat issues :)

> just a proposition but maybe add magic armour sets

If I had a pixel artist...

> definitely more spells

Planned, suggestions are welcome

> plus maybe make spell books of specific type (fire, air, earth, etc.) look different

I use vanilla mechanics for the enchanted books, so this is not possible rn/only with a lot of effort I'm not ready to put in.

> again great mod

Thanks for your feedback :)

**Comment by VanCock** [comment]
Well I actually know a guy who could work as an artist, not sure how good he is in terms of armour but I strongly believe in him, https://www.curseforge.com/members/count_sjorn_paradox/projects
I have noticed a LOT of features in your mod are configurable so maybe let's go for compromise, make mana system a optional feature, both sides are happy this way,
You could add summon spell type, allowing you to summon allies, mounts, n such, but I'm not sure if it would fit this mod as it's very vanilla, maybe self fling, similar to levitate, but faster, wardens echo attack would be kinda cool, charge forward spell is another nice one, maybe like a option to make ennemie fight for you, stealth one just because it's a popular spell in a lot of mods and lastly wither skull and dragons breath ball, oh also could you make 1.19.2 version, a lot of mods are still for this version of the game, thanks and have a good one.  ^^
